name: Push-to-EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      -   run: sudo apt-get install rsync
      -   name: Deploy theme on server
          id: deploy_theme
          uses: Pendect/action-rsyncer@v1.1.0
          env:
              DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          with:
              flags: '-avc --delete'
              src: 'dist/'
              dest: '{{secrets.SERVER_USER}}@"${{secrets.SERVER_IP}}":/home/{{secrets.SERVER_USER}}/trading-bot-interval/'

      -   name: Display status from deploy
          run: echo "${{ steps.deploy.outputs.status }}"
