name: Deploy application on EC2
on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/home/${{ secrets.SERVER_USER }}/trading-bot-interval"

      - uses: actions/checkout@v2

      - name: Removing old python env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: rm /home/${{ secrets.SERVER_USER }}/anaconda3/envs/trading-bot

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run : ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SERVEUR_USE }}@${{ secrets.SERVER_IP }}
      - run: rm /home/${{ secrets.SERVER_USER }}/anaconda3/envs/trading-bot
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda create -n trading-bot python=3.8
      - run: conda activate trading-bot && pip3 install -r requirements.txt
